apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mycr
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - namespaces
  - pods
  - pods/exec
  - persistentvolumeclaims
  - secrets
  - services
  - serviceaccounts
  verbs:
  - '*'
